url: 'http://mogg.local'
simpleProductToBuy: '/jackie-o-round-sunglasses.html'
guestFirstname: 'Otto'
guestLastname: 'Gastbesteller'
guestCompany: 'Gästfirmü'
guestEmail: 'testordner@example.com'
guestStreet1: 'Gaststraße'
guestStreet2: 'zusatzinfo'
guestCity: 'Guest Town'
guestRegion: '1'
guestPostcode: '51234'
guestTelephone: '1234-123123'
guestFax: '1234/1231280'