url: 'http://mogg.local'
# Settings for the homepage test
topCategorys: !!seq [ Women, Men, Accessories, Sale, VIP ]
categorys:
  default:
    Women: !!seq
      - New Arrivals
      - Tops & Blouses
      - Pants & Denim
      - Dresses & Skirts
    Men:
    Accessories:
    Home & Decor:
    Sale:
    VIP:
  german:
    Women: !!seq
      - New Arrivals
      - Tops & Blouses
      - Pants & Denim
      - Dresses & Skirts
    Men:
    Accessories:
    Home & Decor:
    Verkauf:
    VIP:
#Search Test
searchTerm: 'linen'
foundItemCount: 2
#CMS Test
cmsPage: 'about-magento-demo-store'
cmsTitle: 'About Us'
cmsHeadline: 'OUR STORY'

#acount-Test
accountLabel: 'My Account'
registrationPageTitle: 'Create New Customer Account'
registrationHeader: 'CREATE AN ACCOUNT'
registrationRequiredFields:
  - firstname
  - lastname
  - email_address
  - password
  - confirmation
addNewAddressTitle: 'Add New Address'
customerFirstname: 'Richard John'
customerLastname: 'Rebekka'
customerEmail: 'testorder'
customerPassword: 'secret'
customerTelephone: '12341234'
customerStreet: 'Customer Street 1b'
customerZip: '12345'
customerCity: 'Kohlestadt'
customerCountry: 'DE'
customerRegionID: '2'
registrationPasswordMessage: 'Please enter 6 or more characters. Leading or trailing spaces will be ignored.'
registrationPasswordDontMatch: 'Please make sure your passwords match.'
#Settings for checkout-test
simpleProductToBuy: '/jackie-o-round-sunglasses.html'
guestFirstname: 'Otto'
guestLastname: 'Gastbesteller'
guestCompany: 'Gästfirmü'
guestEmail: 'testordner'
guestStreet1: 'Gaststraße'
guestStreet2: 'zusatzinfo'
guestCity: 'Guest Town'
guestRegion: '1'
guestPostcode: '51234'
guestTelephone: '1234-123123'
guestFax: '1234/1231280'

#Settings for the Backendtests
adminUrl: 'regina'
adminUsername: 'darwin'
adminPassword: '2mEnde7'

